steps:
  # Paso 1: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
      - '--build-arg'
      - 'VITE_BACK_URL=${_VITE_BACK_URL}'
      - '.'
    timeout: '1200s'

  # Paso 2: Subir la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'

  # Paso 3: Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'

# Configuración de sustituciones con valores por defecto
substitutions:
  _SERVICE_NAME: 'rag-app-frontend'
  _REGION: 'us-central1'
  _VITE_BACK_URL: 'http://localhost:8000'
  _MEMORY: '512Mi'
  _CPU: '1'
  _MAX_INSTANCES: '10'
  _MIN_INSTANCES: '0'

# Configuración de timeout global
timeout: '1800s'

# Configuración de opciones
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'